const {
  withDangerousMod,
  createRunOncePlugin,
  IOSConfig,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * react-native-readium iOS wiring — the published package has no Expo config plugin.
 *
 * Prebuild must:
 * 1. Add the Readium CocoaPods spec repo (ReadiumShared / Streamer / Navigator live there).
 * 2. Call `readium_pods` so Minizip is a direct dependency.
 * 3. Force modular headers on Minizip — Expo links pods as static libraries, and
 *    `pod 'Minizip', :modular_headers => true` alone is not enough for that.
 * 4. Call `readium_post_install` so Minizip's modulemap survives Nitro's objcxx interop.
 *
 * Android is intentionally untouched (iOS-only for now).
 *
 * `ios/` is gitignored (CNG), so this runs again on every `expo prebuild` / EAS build.
 */
const IOS_MARKER = "# @generated by ./plugins/with-readium";
const READIUM_PODS_CALL = "  readium_pods\n";
const READIUM_POST_INSTALL_CALL = "    readium_post_install(installer)\n";
const READIUM_MINIZIP_HOOK = "    # @generated by ./plugins/with-readium: Minizip modular headers\n";
const READIUM_SPEC_SOURCE = "https://github.com/readium/podspecs";
const COCOAPODS_CDN_SOURCE = "https://cdn.cocoapods.org/";

const MINIZIP_PRE_INSTALL = `  pre_install do |installer|
${READIUM_MINIZIP_HOOK}    installer.podfile.target_definition_list.each do |target_def|
      target_def.set_use_modular_headers_for_pod('Minizip', true)
    end
  end

`;

const createIosSetup = (iosProjectRoot) => {
  const packageRoot = path.dirname(
    require.resolve("react-native-readium/package.json"),
  );
  const relativePackageRoot = path
    .relative(iosProjectRoot, packageRoot)
    .replaceAll(path.sep, "/");

  return [
    IOS_MARKER,
    `source '${READIUM_SPEC_SOURCE}'`,
    `source '${COCOAPODS_CDN_SOURCE}'`,
    `readium_package_path = File.expand_path('${relativePackageRoot}', __dir__)`,
    "require File.join(readium_package_path, 'scripts/readium_pods')",
    "require File.join(readium_package_path, 'scripts/readium_post_install')",
    "",
  ].join("\n");
};

const insertAfterFirstMatch = (contents, pattern, insertion) => {
  const match = contents.match(pattern);
  if (!match || match.index === undefined) {
    return null;
  }
  const at = match.index + match[0].length;
  return `${contents.slice(0, at)}${insertion}${contents.slice(at)}`;
};

const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const withReadiumPods = (config) => {
  const appTargetName = IOSConfig.XcodeUtils.sanitizedName(config.name ?? "");

  return withDangerousMod(config, [
    "ios",
    async (modConfig) => {
      const podfilePath = path.join(
        modConfig.modRequest.platformProjectRoot,
        "Podfile",
      );
      const setup = createIosSetup(modConfig.modRequest.platformProjectRoot);
      let contents = fs.readFileSync(podfilePath, "utf8");

      if (!contents.includes(IOS_MARKER)) {
        contents = `${setup}${contents}`;
      }

      if (!contents.includes(READIUM_PODS_CALL)) {
        const withPods = insertAfterFirstMatch(
          contents,
          /use_expo_modules!\n/,
          READIUM_PODS_CALL,
        );
        if (!withPods) {
          throw new Error(
            "with-readium could not find use_expo_modules! in the iOS Podfile.",
          );
        }
        contents = withPods;
      }

      if (!contents.includes(READIUM_MINIZIP_HOOK)) {
        const withPreInstall = insertAfterFirstMatch(
          contents,
          new RegExp(`target '${escapeRegExp(appTargetName)}' do\\n`),
          MINIZIP_PRE_INSTALL,
        );
        if (!withPreInstall) {
          throw new Error(
            `with-readium could not find target '${appTargetName}' in the iOS Podfile.`,
          );
        }
        contents = withPreInstall;
      }

      if (!contents.includes(READIUM_POST_INSTALL_CALL)) {
        const withPostInstall = insertAfterFirstMatch(
          contents,
          /\n\s*post_install do \|installer\|\s*\n/,
          READIUM_POST_INSTALL_CALL,
        );
        if (!withPostInstall) {
          throw new Error(
            "with-readium could not find the CocoaPods post_install block in the iOS Podfile.",
          );
        }
        contents = withPostInstall;
      }

      fs.writeFileSync(podfilePath, contents);
      return modConfig;
    },
  ]);
};

module.exports = createRunOncePlugin(withReadiumPods, "with-readium", "1.0.0");
